// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: license/license.proto

package license

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 免許証データ
type LicenseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                        // カードID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                          // 氏名
	NameKana      string                 `protobuf:"bytes,3,opt,name=name_kana,json=nameKana,proto3" json:"name_kana,omitempty"`                  // 氏名（カナ）
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`               // 生年月日 (YYYY-MM-DD)
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                                    // 住所
	IssueDate     string                 `protobuf:"bytes,6,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`               // 交付日 (YYYY-MM-DD)
	ExpiryDate    string                 `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`            // 有効期限 (YYYY-MM-DD)
	LicenseNumber string                 `protobuf:"bytes,8,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`   // 免許証番号
	LicenseType   string                 `protobuf:"bytes,9,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`         // 免許種別
	Photo         []byte                 `protobuf:"bytes,10,opt,name=photo,proto3" json:"photo,omitempty"`                                       // 顔写真データ
	ReadTimestamp int64                  `protobuf:"varint,11,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"` // 読み取りタイムスタンプ (Unix時刻)
	ReaderId      string                 `protobuf:"bytes,12,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`                 // リーダーID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseData) Reset() {
	*x = LicenseData{}
	mi := &file_license_license_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseData) ProtoMessage() {}

func (x *LicenseData) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseData.ProtoReflect.Descriptor instead.
func (*LicenseData) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{0}
}

func (x *LicenseData) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *LicenseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LicenseData) GetNameKana() string {
	if x != nil {
		return x.NameKana
	}
	return ""
}

func (x *LicenseData) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *LicenseData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LicenseData) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *LicenseData) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *LicenseData) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *LicenseData) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *LicenseData) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *LicenseData) GetReadTimestamp() int64 {
	if x != nil {
		return x.ReadTimestamp
	}
	return 0
}

func (x *LicenseData) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

// 読み取りログ
type ReadLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // タイムスタンプ
	ReaderId      string                 `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`             // リーダーID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                 // ステータス (success/error)
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // エラーメッセージ（エラー時）
	CardId        string                 `protobuf:"bytes,5,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                   // カードID（成功時）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLog) Reset() {
	*x = ReadLog{}
	mi := &file_license_license_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLog) ProtoMessage() {}

func (x *ReadLog) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLog.ProtoReflect.Descriptor instead.
func (*ReadLog) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{1}
}

func (x *ReadLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReadLog) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *ReadLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReadLog) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// レスポンス
type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // リクエストID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_license_license_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{2}
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ログ取得リクエスト
type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReaderId      string                 `protobuf:"bytes,1,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`     // リーダーID（省略時は全リーダー）
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                           // ログレベル（INFO/WARNING/ERROR/DEBUG）
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 開始時刻（Unix時刻）
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 終了時刻（Unix時刻）
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                          // 取得件数制限（デフォルト100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_license_license_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{3}
}

func (x *GetLogsRequest) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *GetLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ログ取得レスポンス
type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 総件数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_license_license_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ログエントリ
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // タイムスタンプ（Unix時刻）
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                       // ログレベル
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // ログメッセージ
	ReaderId      string                 `protobuf:"bytes,4,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"` // リーダーID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_license_license_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

// 読み取り履歴取得リクエスト
type GetReadHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReaderId      string                 `protobuf:"bytes,1,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`     // リーダーID（省略時は全リーダー）
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                         // ステータス（success/error）
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 開始時刻（Unix時刻）
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 終了時刻（Unix時刻）
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                          // 取得件数制限（デフォルト100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadHistoryRequest) Reset() {
	*x = GetReadHistoryRequest{}
	mi := &file_license_license_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadHistoryRequest) ProtoMessage() {}

func (x *GetReadHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetReadHistoryRequest) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{6}
}

func (x *GetReadHistoryRequest) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *GetReadHistoryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReadHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetReadHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetReadHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 読み取り履歴取得レスポンス
type GetReadHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReadHistoryEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 総件数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadHistoryResponse) Reset() {
	*x = GetReadHistoryResponse{}
	mi := &file_license_license_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadHistoryResponse) ProtoMessage() {}

func (x *GetReadHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetReadHistoryResponse) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{7}
}

func (x *GetReadHistoryResponse) GetEntries() []*ReadHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetReadHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 読み取り履歴エントリ
type ReadHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // タイムスタンプ（Unix時刻）
	ReaderId      string                 `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`              // リーダーID
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                    // カードID
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`              // カード種別
	Atr           string                 `protobuf:"bytes,5,opt,name=atr,proto3" json:"atr,omitempty"`                                        // ATR
	ExpiryDate    string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`        // 有効期限
	RemainCount   string                 `protobuf:"bytes,7,opt,name=remain_count,json=remainCount,proto3" json:"remain_count,omitempty"`     // 残り回数
	FelicaUid     string                 `protobuf:"bytes,8,opt,name=felica_uid,json=felicaUid,proto3" json:"felica_uid,omitempty"`           // FeliCa UID
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                  // ステータス（success/error）
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // エラーメッセージ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadHistoryEntry) Reset() {
	*x = ReadHistoryEntry{}
	mi := &file_license_license_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHistoryEntry) ProtoMessage() {}

func (x *ReadHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_license_license_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHistoryEntry.ProtoReflect.Descriptor instead.
func (*ReadHistoryEntry) Descriptor() ([]byte, []int) {
	return file_license_license_proto_rawDescGZIP(), []int{8}
}

func (x *ReadHistoryEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReadHistoryEntry) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *ReadHistoryEntry) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ReadHistoryEntry) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *ReadHistoryEntry) GetAtr() string {
	if x != nil {
		return x.Atr
	}
	return ""
}

func (x *ReadHistoryEntry) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *ReadHistoryEntry) GetRemainCount() string {
	if x != nil {
		return x.RemainCount
	}
	return ""
}

func (x *ReadHistoryEntry) GetFelicaUid() string {
	if x != nil {
		return x.FelicaUid
	}
	return ""
}

func (x *ReadHistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadHistoryEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_license_license_proto protoreflect.FileDescriptor

const file_license_license_proto_rawDesc = "" +
	"\n" +
	"\x15license/license.proto\x12\alicense\"\xf4\x02\n" +
	"\vLicenseData\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tname_kana\x18\x03 \x01(\tR\bnameKana\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x06 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\a \x01(\tR\n" +
	"expiryDate\x12%\n" +
	"\x0elicense_number\x18\b \x01(\tR\rlicenseNumber\x12!\n" +
	"\flicense_type\x18\t \x01(\tR\vlicenseType\x12\x14\n" +
	"\x05photo\x18\n" +
	" \x01(\fR\x05photo\x12%\n" +
	"\x0eread_timestamp\x18\v \x01(\x03R\rreadTimestamp\x12\x1b\n" +
	"\treader_id\x18\f \x01(\tR\breaderId\"\x9a\x01\n" +
	"\aReadLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\treader_id\x18\x02 \x01(\tR\breaderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\acard_id\x18\x05 \x01(\tR\x06cardId\"a\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x93\x01\n" +
	"\x0eGetLogsRequest\x12\x1b\n" +
	"\treader_id\x18\x01 \x01(\tR\breaderId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"Y\n" +
	"\x0fGetLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.license.LogEntryR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"u\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\treader_id\x18\x04 \x01(\tR\breaderId\"\x9c\x01\n" +
	"\x15GetReadHistoryRequest\x12\x1b\n" +
	"\treader_id\x18\x01 \x01(\tR\breaderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"n\n" +
	"\x16GetReadHistoryResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.license.ReadHistoryEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb5\x02\n" +
	"\x10ReadHistoryEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\treader_id\x18\x02 \x01(\tR\breaderId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x10\n" +
	"\x03atr\x18\x05 \x01(\tR\x03atr\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12!\n" +
	"\fremain_count\x18\a \x01(\tR\vremainCount\x12\x1d\n" +
	"\n" +
	"felica_uid\x18\b \x01(\tR\tfelicaUid\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage2\x98\x02\n" +
	"\rLicenseReader\x12>\n" +
	"\x0fPushLicenseData\x12\x14.license.LicenseData\x1a\x15.license.PushResponse\x126\n" +
	"\vPushReadLog\x12\x10.license.ReadLog\x1a\x15.license.PushResponse\x12<\n" +
	"\aGetLogs\x12\x17.license.GetLogsRequest\x1a\x18.license.GetLogsResponse\x12Q\n" +
	"\x0eGetReadHistory\x12\x1e.license.GetReadHistoryRequest\x1a\x1f.license.GetReadHistoryResponseB\x19Z\x17menkyo_go/proto/licenseb\x06proto3"

var (
	file_license_license_proto_rawDescOnce sync.Once
	file_license_license_proto_rawDescData []byte
)

func file_license_license_proto_rawDescGZIP() []byte {
	file_license_license_proto_rawDescOnce.Do(func() {
		file_license_license_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_license_license_proto_rawDesc), len(file_license_license_proto_rawDesc)))
	})
	return file_license_license_proto_rawDescData
}

var file_license_license_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_license_license_proto_goTypes = []any{
	(*LicenseData)(nil),            // 0: license.LicenseData
	(*ReadLog)(nil),                // 1: license.ReadLog
	(*PushResponse)(nil),           // 2: license.PushResponse
	(*GetLogsRequest)(nil),         // 3: license.GetLogsRequest
	(*GetLogsResponse)(nil),        // 4: license.GetLogsResponse
	(*LogEntry)(nil),               // 5: license.LogEntry
	(*GetReadHistoryRequest)(nil),  // 6: license.GetReadHistoryRequest
	(*GetReadHistoryResponse)(nil), // 7: license.GetReadHistoryResponse
	(*ReadHistoryEntry)(nil),       // 8: license.ReadHistoryEntry
}
var file_license_license_proto_depIdxs = []int32{
	5, // 0: license.GetLogsResponse.logs:type_name -> license.LogEntry
	8, // 1: license.GetReadHistoryResponse.entries:type_name -> license.ReadHistoryEntry
	0, // 2: license.LicenseReader.PushLicenseData:input_type -> license.LicenseData
	1, // 3: license.LicenseReader.PushReadLog:input_type -> license.ReadLog
	3, // 4: license.LicenseReader.GetLogs:input_type -> license.GetLogsRequest
	6, // 5: license.LicenseReader.GetReadHistory:input_type -> license.GetReadHistoryRequest
	2, // 6: license.LicenseReader.PushLicenseData:output_type -> license.PushResponse
	2, // 7: license.LicenseReader.PushReadLog:output_type -> license.PushResponse
	4, // 8: license.LicenseReader.GetLogs:output_type -> license.GetLogsResponse
	7, // 9: license.LicenseReader.GetReadHistory:output_type -> license.GetReadHistoryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_license_license_proto_init() }
func file_license_license_proto_init() {
	if File_license_license_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_license_license_proto_rawDesc), len(file_license_license_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_license_license_proto_goTypes,
		DependencyIndexes: file_license_license_proto_depIdxs,
		MessageInfos:      file_license_license_proto_msgTypes,
	}.Build()
	File_license_license_proto = out.File
	file_license_license_proto_goTypes = nil
	file_license_license_proto_depIdxs = nil
}
