// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRole defines the available user roles
type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0 // Default/unspecified role
	UserRole_USER_ROLE_ADMIN       UserRole = 1 // Administrator with full access
	UserRole_USER_ROLE_MAINTAINER  UserRole = 2 // Maintainer with limited admin access
	UserRole_USER_ROLE_USER        UserRole = 3 // Regular user
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_ADMIN",
		2: "USER_ROLE_MAINTAINER",
		3: "USER_ROLE_USER",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_ADMIN":       1,
		"USER_ROLE_MAINTAINER":  2,
		"USER_ROLE_USER":        3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// DBEnvironment specifies which database to use
type DBEnvironment int32

const (
	DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED DBEnvironment = 0 // Default (uses prod)
	DBEnvironment_DB_ENVIRONMENT_PROD        DBEnvironment = 1 // Production DB (read-only)
	DBEnvironment_DB_ENVIRONMENT_DEV         DBEnvironment = 2 // Development DB (read-write)
)

// Enum value maps for DBEnvironment.
var (
	DBEnvironment_name = map[int32]string{
		0: "DB_ENVIRONMENT_UNSPECIFIED",
		1: "DB_ENVIRONMENT_PROD",
		2: "DB_ENVIRONMENT_DEV",
	}
	DBEnvironment_value = map[string]int32{
		"DB_ENVIRONMENT_UNSPECIFIED": 0,
		"DB_ENVIRONMENT_PROD":        1,
		"DB_ENVIRONMENT_DEV":         2,
	}
)

func (x DBEnvironment) Enum() *DBEnvironment {
	p := new(DBEnvironment)
	*p = x
	return p
}

func (x DBEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DBEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (DBEnvironment) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[1]
}

func (x DBEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DBEnvironment.Descriptor instead.
func (DBEnvironment) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

// Request to get OAuth authorization URL
type GetAuthorizationURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "woff" or "line" (default: "woff")
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`   // CSRF protection state
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"` // Optional scopes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorizationURLRequest) Reset() {
	*x = GetAuthorizationURLRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationURLRequest) ProtoMessage() {}

func (x *GetAuthorizationURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationURLRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationURLRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthorizationURLRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetAuthorizationURLRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GetAuthorizationURLRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetAuthorizationURLRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// Response containing the authorization URL
type GetAuthorizationURLResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAuthorizationURLResponse) Reset() {
	*x = GetAuthorizationURLResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorizationURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationURLResponse) ProtoMessage() {}

func (x *GetAuthorizationURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationURLResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationURLResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorizationURLResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *GetAuthorizationURLResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Request to exchange authorization code for tokens
type ExchangeCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "woff" or "line" (default: "woff")
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // CSRF verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCodeRequest) Reset() {
	*x = ExchangeCodeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeRequest) ProtoMessage() {}

func (x *ExchangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeCodeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExchangeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *ExchangeCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Response containing OAuth access tokens and user info
type ExchangeCodeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccessToken  string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn    int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType    string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope        []string               `protobuf:"bytes,5,rep,name=scope,proto3" json:"scope,omitempty"`
	// User information (included for convenience)
	UserId          string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider        string   `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"` // "woff" or "line"
	UserName        string   `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email           string   `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName     string   `protobuf:"bytes,10,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DomainId        string   `protobuf:"bytes,11,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Roles           []string `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles,omitempty"`
	ProfileImageUrl string   `protobuf:"bytes,13,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExchangeCodeResponse) Reset() {
	*x = ExchangeCodeResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeResponse) ProtoMessage() {}

func (x *ExchangeCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeCodeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeCodeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeCodeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeCodeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeCodeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeCodeResponse) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ExchangeCodeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExchangeCodeResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExchangeCodeResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ExchangeCodeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExchangeCodeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ExchangeCodeResponse) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *ExchangeCodeResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ExchangeCodeResponse) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

type GetProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // "woff" or "line"
	UserName        string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName     string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DomainId        string                 `protobuf:"bytes,6,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Roles           []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,8,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetProfileResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetProfileResponse) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *GetProfileResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetProfileResponse) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *RefreshTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VerifyTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListUsersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                           // Page number (default: 1)
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                   // Number of users per page (default: 50, max: 100)
	IncludeDeleted bool                   `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"` // Include soft-deleted users (default: false)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // "woff" or "line"
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"` // New roles to set for the user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRolesRequest) Reset() {
	*x = UpdateUserRolesRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRolesRequest) ProtoMessage() {}

func (x *UpdateUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRolesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRolesRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"` // Updated roles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRolesResponse) Reset() {
	*x = UpdateUserRolesResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRolesResponse) ProtoMessage() {}

func (x *UpdateUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRolesResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRolesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserRolesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserRolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreUserRequest) Reset() {
	*x = RestoreUserRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreUserRequest) ProtoMessage() {}

func (x *RestoreUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreUserRequest.ProtoReflect.Descriptor instead.
func (*RestoreUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *RestoreUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RestoreUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreUserResponse) Reset() {
	*x = RestoreUserResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreUserResponse) ProtoMessage() {}

func (x *RestoreUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreUserResponse.ProtoReflect.Descriptor instead.
func (*RestoreUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TimeCard represents a single timecard entry
type TimeCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID
	MachineIp     string                 `protobuf:"bytes,3,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,5,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	Created       string                 `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`                            // RFC3339 format timestamp
	Modified      string                 `protobuf:"bytes,7,opt,name=modified,proto3" json:"modified,omitempty"`                          // RFC3339 format timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCard) Reset() {
	*x = TimeCard{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCard) ProtoMessage() {}

func (x *TimeCard) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCard.ProtoReflect.Descriptor instead.
func (*TimeCard) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *TimeCard) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *TimeCard) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimeCard) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *TimeCard) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TimeCard) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

func (x *TimeCard) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *TimeCard) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// GetTimeCardRequest requests a specific timecard by composite key
type GetTimeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   DBEnvironment          `protobuf:"varint,1,opt,name=environment,proto3,enum=auth.v1.DBEnvironment" json:"environment,omitempty"` // Which database to use
	Datetime      string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`                                   // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                              // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeCardRequest) Reset() {
	*x = GetTimeCardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeCardRequest) ProtoMessage() {}

func (x *GetTimeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeCardRequest.ProtoReflect.Descriptor instead.
func (*GetTimeCardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *GetTimeCardRequest) GetEnvironment() DBEnvironment {
	if x != nil {
		return x.Environment
	}
	return DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED
}

func (x *GetTimeCardRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *GetTimeCardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TimeCardResponse returns a single timecard
type TimeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timecard      *TimeCard              `protobuf:"bytes,1,opt,name=timecard,proto3" json:"timecard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCardResponse) Reset() {
	*x = TimeCardResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCardResponse) ProtoMessage() {}

func (x *TimeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCardResponse.ProtoReflect.Descriptor instead.
func (*TimeCardResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *TimeCardResponse) GetTimecard() *TimeCard {
	if x != nil {
		return x.Timecard
	}
	return nil
}

// ListTimeCardsRequest requests a list of timecards
type ListTimeCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   DBEnvironment          `protobuf:"varint,1,opt,name=environment,proto3,enum=auth.v1.DBEnvironment" json:"environment,omitempty"` // Which database to use
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Number of records to return (default: 50, max: 100)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Number of records to skip (default: 0)
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                      // Order by field (default: "datetime DESC")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeCardsRequest) Reset() {
	*x = ListTimeCardsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeCardsRequest) ProtoMessage() {}

func (x *ListTimeCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeCardsRequest.ProtoReflect.Descriptor instead.
func (*ListTimeCardsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *ListTimeCardsRequest) GetEnvironment() DBEnvironment {
	if x != nil {
		return x.Environment
	}
	return DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED
}

func (x *ListTimeCardsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTimeCardsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTimeCardsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListTimeCardsResponse returns a list of timecards
type ListTimeCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timecards     []*TimeCard            `protobuf:"bytes,1,rep,name=timecards,proto3" json:"timecards,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of timecards
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeCardsResponse) Reset() {
	*x = ListTimeCardsResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeCardsResponse) ProtoMessage() {}

func (x *ListTimeCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeCardsResponse.ProtoReflect.Descriptor instead.
func (*ListTimeCardsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *ListTimeCardsResponse) GetTimecards() []*TimeCard {
	if x != nil {
		return x.Timecards
	}
	return nil
}

func (x *ListTimeCardsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreateTimeCardRequest creates a new timecard (dev only)
type CreateTimeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID
	MachineIp     string                 `protobuf:"bytes,3,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,5,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimeCardRequest) Reset() {
	*x = CreateTimeCardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeCardRequest) ProtoMessage() {}

func (x *CreateTimeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeCardRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeCardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTimeCardRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *CreateTimeCardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTimeCardRequest) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *CreateTimeCardRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateTimeCardRequest) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

// UpdateTimeCardRequest updates an existing timecard (dev only)
type UpdateTimeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp (part of composite key)
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID (part of composite key)
	MachineIp     string                 `protobuf:"bytes,3,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,5,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeCardRequest) Reset() {
	*x = UpdateTimeCardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeCardRequest) ProtoMessage() {}

func (x *UpdateTimeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimeCardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTimeCardRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *UpdateTimeCardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTimeCardRequest) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *UpdateTimeCardRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateTimeCardRequest) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

// DeleteTimeCardRequest deletes a timecard (dev only)
type DeleteTimeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"` // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTimeCardRequest) Reset() {
	*x = DeleteTimeCardRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTimeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimeCardRequest) ProtoMessage() {}

func (x *DeleteTimeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimeCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteTimeCardRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteTimeCardRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *DeleteTimeCardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTimeCardResponse confirms deletion
type DeleteTimeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTimeCardResponse) Reset() {
	*x = DeleteTimeCardResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTimeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimeCardResponse) ProtoMessage() {}

func (x *DeleteTimeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimeCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteTimeCardResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteTimeCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTimeCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TimeCardLog represents a single timecard log entry
type TimeCardLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                // Card ID (FeliCa UID etc.)
	MachineIp     string                 `protobuf:"bytes,4,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,6,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	Created       string                 `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`                            // RFC3339 format timestamp
	Modified      string                 `protobuf:"bytes,8,opt,name=modified,proto3" json:"modified,omitempty"`                          // RFC3339 format timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCardLog) Reset() {
	*x = TimeCardLog{}
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCardLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCardLog) ProtoMessage() {}

func (x *TimeCardLog) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCardLog.ProtoReflect.Descriptor instead.
func (*TimeCardLog) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{28}
}

func (x *TimeCardLog) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *TimeCardLog) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimeCardLog) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *TimeCardLog) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *TimeCardLog) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TimeCardLog) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

func (x *TimeCardLog) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *TimeCardLog) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// GetTimeCardLogRequest requests a specific timecard log by composite key
type GetTimeCardLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   DBEnvironment          `protobuf:"varint,1,opt,name=environment,proto3,enum=auth.v1.DBEnvironment" json:"environment,omitempty"` // Which database to use
	Datetime      string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`                                   // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                              // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeCardLogRequest) Reset() {
	*x = GetTimeCardLogRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeCardLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeCardLogRequest) ProtoMessage() {}

func (x *GetTimeCardLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeCardLogRequest.ProtoReflect.Descriptor instead.
func (*GetTimeCardLogRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{29}
}

func (x *GetTimeCardLogRequest) GetEnvironment() DBEnvironment {
	if x != nil {
		return x.Environment
	}
	return DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED
}

func (x *GetTimeCardLogRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *GetTimeCardLogRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TimeCardLogResponse returns a single timecard log
type TimeCardLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *TimeCardLog           `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeCardLogResponse) Reset() {
	*x = TimeCardLogResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeCardLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeCardLogResponse) ProtoMessage() {}

func (x *TimeCardLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeCardLogResponse.ProtoReflect.Descriptor instead.
func (*TimeCardLogResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{30}
}

func (x *TimeCardLogResponse) GetLog() *TimeCardLog {
	if x != nil {
		return x.Log
	}
	return nil
}

// ListTimeCardLogsRequest requests a list of timecard logs
type ListTimeCardLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   DBEnvironment          `protobuf:"varint,1,opt,name=environment,proto3,enum=auth.v1.DBEnvironment" json:"environment,omitempty"` // Which database to use
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Number of records to return (default: 50, max: 100)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Number of records to skip (default: 0)
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                      // Order by field (default: "datetime DESC")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeCardLogsRequest) Reset() {
	*x = ListTimeCardLogsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeCardLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeCardLogsRequest) ProtoMessage() {}

func (x *ListTimeCardLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeCardLogsRequest.ProtoReflect.Descriptor instead.
func (*ListTimeCardLogsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{31}
}

func (x *ListTimeCardLogsRequest) GetEnvironment() DBEnvironment {
	if x != nil {
		return x.Environment
	}
	return DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED
}

func (x *ListTimeCardLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTimeCardLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTimeCardLogsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListTimeCardLogsByCardIDRequest requests timecard logs by card_id
type ListTimeCardLogsByCardIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   DBEnvironment          `protobuf:"varint,1,opt,name=environment,proto3,enum=auth.v1.DBEnvironment" json:"environment,omitempty"` // Which database to use
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                         // Card ID to filter by
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // Number of records to return (default: 50, max: 100)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                      // Number of records to skip (default: 0)
	OrderBy       string                 `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                      // Order by field (default: "datetime DESC")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeCardLogsByCardIDRequest) Reset() {
	*x = ListTimeCardLogsByCardIDRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeCardLogsByCardIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeCardLogsByCardIDRequest) ProtoMessage() {}

func (x *ListTimeCardLogsByCardIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeCardLogsByCardIDRequest.ProtoReflect.Descriptor instead.
func (*ListTimeCardLogsByCardIDRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{32}
}

func (x *ListTimeCardLogsByCardIDRequest) GetEnvironment() DBEnvironment {
	if x != nil {
		return x.Environment
	}
	return DBEnvironment_DB_ENVIRONMENT_UNSPECIFIED
}

func (x *ListTimeCardLogsByCardIDRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ListTimeCardLogsByCardIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTimeCardLogsByCardIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTimeCardLogsByCardIDRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListTimeCardLogsResponse returns a list of timecard logs
type ListTimeCardLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*TimeCardLog         `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimeCardLogsResponse) Reset() {
	*x = ListTimeCardLogsResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimeCardLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimeCardLogsResponse) ProtoMessage() {}

func (x *ListTimeCardLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimeCardLogsResponse.ProtoReflect.Descriptor instead.
func (*ListTimeCardLogsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{33}
}

func (x *ListTimeCardLogsResponse) GetLogs() []*TimeCardLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListTimeCardLogsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreateTimeCardLogRequest creates a new timecard log (dev only)
type CreateTimeCardLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                // Card ID (FeliCa UID etc.)
	MachineIp     string                 `protobuf:"bytes,4,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,6,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimeCardLogRequest) Reset() {
	*x = CreateTimeCardLogRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimeCardLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeCardLogRequest) ProtoMessage() {}

func (x *CreateTimeCardLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeCardLogRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeCardLogRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{34}
}

func (x *CreateTimeCardLogRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *CreateTimeCardLogRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTimeCardLogRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CreateTimeCardLogRequest) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *CreateTimeCardLogRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateTimeCardLogRequest) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

// UpdateTimeCardLogRequest updates an existing timecard log (dev only)
type UpdateTimeCardLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`                          // RFC3339 format timestamp (part of composite key)
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                                     // User ID (part of composite key)
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`                // Card ID (FeliCa UID etc.)
	MachineIp     string                 `protobuf:"bytes,4,opt,name=machine_ip,json=machineIp,proto3" json:"machine_ip,omitempty"`       // Machine IP address
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                // State (e.g., "in", "out")
	StateDetail   string                 `protobuf:"bytes,6,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"` // Optional state detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeCardLogRequest) Reset() {
	*x = UpdateTimeCardLogRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeCardLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeCardLogRequest) ProtoMessage() {}

func (x *UpdateTimeCardLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeCardLogRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimeCardLogRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateTimeCardLogRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *UpdateTimeCardLogRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTimeCardLogRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateTimeCardLogRequest) GetMachineIp() string {
	if x != nil {
		return x.MachineIp
	}
	return ""
}

func (x *UpdateTimeCardLogRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateTimeCardLogRequest) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

// DeleteTimeCardLogRequest deletes a timecard log (dev only)
type DeleteTimeCardLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datetime      string                 `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"` // RFC3339 format timestamp
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTimeCardLogRequest) Reset() {
	*x = DeleteTimeCardLogRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTimeCardLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimeCardLogRequest) ProtoMessage() {}

func (x *DeleteTimeCardLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimeCardLogRequest.ProtoReflect.Descriptor instead.
func (*DeleteTimeCardLogRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteTimeCardLogRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *DeleteTimeCardLogRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTimeCardLogResponse confirms deletion
type DeleteTimeCardLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTimeCardLogResponse) Reset() {
	*x = DeleteTimeCardLogResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTimeCardLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimeCardLogResponse) ProtoMessage() {}

func (x *DeleteTimeCardLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimeCardLogResponse.ProtoReflect.Descriptor instead.
func (*DeleteTimeCardLogResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteTimeCardLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTimeCardLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\"\x89\x01\n" +
	"\x1aGetAuthorizationURLRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"`\n" +
	"\x1bGetAuthorizationURLResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"~\n" +
	"\x13ExchangeCodeRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\x9c\x03\n" +
	"\x14ExchangeCodeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x05 \x03(\tR\x05scope\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12\x1b\n" +
	"\tuser_name\x18\b \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\n" +
	" \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tdomain_id\x18\v \x01(\tR\bdomainId\x12\x14\n" +
	"\x05roles\x18\f \x03(\tR\x05roles\x12*\n" +
	"\x11profile_image_url\x18\r \x01(\tR\x0fprofileImageUrl\"\x13\n" +
	"\x11GetProfileRequest\"\xfe\x01\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tdomain_id\x18\x06 \x01(\tR\bdomainId\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05roles\x12*\n" +
	"\x11profile_image_url\x18\b \x01(\tR\x0fprofileImageUrl\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"w\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"{\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"l\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12'\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bR\x0eincludeDeleted\"\xee\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\"\x8a\x01\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.auth.v1.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"G\n" +
	"\x16UpdateUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"c\n" +
	"\x17UpdateUserRolesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12RestoreUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x13RestoreUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\bTimeCard\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x03 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x05 \x01(\tR\vstateDetail\x12\x18\n" +
	"\acreated\x18\x06 \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\a \x01(\tR\bmodified\"z\n" +
	"\x12GetTimeCardRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.auth.v1.DBEnvironmentR\venvironment\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"A\n" +
	"\x10TimeCardResponse\x12-\n" +
	"\btimecard\x18\x01 \x01(\v2\x11.auth.v1.TimeCardR\btimecard\"\x99\x01\n" +
	"\x14ListTimeCardsRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.auth.v1.DBEnvironmentR\venvironment\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"i\n" +
	"\x15ListTimeCardsResponse\x12/\n" +
	"\ttimecards\x18\x01 \x03(\v2\x11.auth.v1.TimeCardR\ttimecards\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\x9b\x01\n" +
	"\x15CreateTimeCardRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x03 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x05 \x01(\tR\vstateDetail\"\x9b\x01\n" +
	"\x15UpdateTimeCardRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x03 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x05 \x01(\tR\vstateDetail\"C\n" +
	"\x15DeleteTimeCardRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"L\n" +
	"\x16DeleteTimeCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x01\n" +
	"\vTimeCardLog\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x04 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x06 \x01(\tR\vstateDetail\x12\x18\n" +
	"\acreated\x18\a \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\b \x01(\tR\bmodified\"}\n" +
	"\x15GetTimeCardLogRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.auth.v1.DBEnvironmentR\venvironment\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"=\n" +
	"\x13TimeCardLogResponse\x12&\n" +
	"\x03log\x18\x01 \x01(\v2\x14.auth.v1.TimeCardLogR\x03log\"\x9c\x01\n" +
	"\x17ListTimeCardLogsRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.auth.v1.DBEnvironmentR\venvironment\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\xbd\x01\n" +
	"\x1fListTimeCardLogsByCardIDRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.auth.v1.DBEnvironmentR\venvironment\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\"e\n" +
	"\x18ListTimeCardLogsResponse\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.auth.v1.TimeCardLogR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xb7\x01\n" +
	"\x18CreateTimeCardLogRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x04 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x06 \x01(\tR\vstateDetail\"\xb7\x01\n" +
	"\x18UpdateTimeCardLogRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"machine_ip\x18\x04 \x01(\tR\tmachineIp\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12!\n" +
	"\fstate_detail\x18\x06 \x01(\tR\vstateDetail\"F\n" +
	"\x18DeleteTimeCardLogRequest\x12\x1a\n" +
	"\bdatetime\x18\x01 \x01(\tR\bdatetime\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"O\n" +
	"\x19DeleteTimeCardLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*h\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01\x12\x18\n" +
	"\x14USER_ROLE_MAINTAINER\x10\x02\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x03*`\n" +
	"\rDBEnvironment\x12\x1e\n" +
	"\x1aDB_ENVIRONMENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DB_ENVIRONMENT_PROD\x10\x01\x12\x16\n" +
	"\x12DB_ENVIRONMENT_DEV\x10\x022\xe3\f\n" +
	"\vAuthService\x12`\n" +
	"\x13GetAuthorizationURL\x12#.auth.v1.GetAuthorizationURLRequest\x1a$.auth.v1.GetAuthorizationURLResponse\x12K\n" +
	"\fExchangeCode\x12\x1c.auth.v1.ExchangeCodeRequest\x1a\x1d.auth.v1.ExchangeCodeResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.auth.v1.GetProfileRequest\x1a\x1b.auth.v1.GetProfileResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\x12H\n" +
	"\vVerifyToken\x12\x1b.auth.v1.VerifyTokenRequest\x1a\x1c.auth.v1.VerifyTokenResponse\x12B\n" +
	"\tListUsers\x12\x19.auth.v1.ListUsersRequest\x1a\x1a.auth.v1.ListUsersResponse\x12T\n" +
	"\x0fUpdateUserRoles\x12\x1f.auth.v1.UpdateUserRolesRequest\x1a .auth.v1.UpdateUserRolesResponse\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.auth.v1.DeleteUserRequest\x1a\x1b.auth.v1.DeleteUserResponse\x12H\n" +
	"\vRestoreUser\x12\x1b.auth.v1.RestoreUserRequest\x1a\x1c.auth.v1.RestoreUserResponse\x12E\n" +
	"\vGetTimeCard\x12\x1b.auth.v1.GetTimeCardRequest\x1a\x19.auth.v1.TimeCardResponse\x12N\n" +
	"\rListTimeCards\x12\x1d.auth.v1.ListTimeCardsRequest\x1a\x1e.auth.v1.ListTimeCardsResponse\x12K\n" +
	"\x0eCreateTimeCard\x12\x1e.auth.v1.CreateTimeCardRequest\x1a\x19.auth.v1.TimeCardResponse\x12K\n" +
	"\x0eUpdateTimeCard\x12\x1e.auth.v1.UpdateTimeCardRequest\x1a\x19.auth.v1.TimeCardResponse\x12Q\n" +
	"\x0eDeleteTimeCard\x12\x1e.auth.v1.DeleteTimeCardRequest\x1a\x1f.auth.v1.DeleteTimeCardResponse\x12N\n" +
	"\x0eGetTimeCardLog\x12\x1e.auth.v1.GetTimeCardLogRequest\x1a\x1c.auth.v1.TimeCardLogResponse\x12W\n" +
	"\x10ListTimeCardLogs\x12 .auth.v1.ListTimeCardLogsRequest\x1a!.auth.v1.ListTimeCardLogsResponse\x12g\n" +
	"\x18ListTimeCardLogsByCardID\x12(.auth.v1.ListTimeCardLogsByCardIDRequest\x1a!.auth.v1.ListTimeCardLogsResponse\x12T\n" +
	"\x11CreateTimeCardLog\x12!.auth.v1.CreateTimeCardLogRequest\x1a\x1c.auth.v1.TimeCardLogResponse\x12T\n" +
	"\x11UpdateTimeCardLog\x12!.auth.v1.UpdateTimeCardLogRequest\x1a\x1c.auth.v1.TimeCardLogResponse\x12Z\n" +
	"\x11DeleteTimeCardLog\x12!.auth.v1.DeleteTimeCardLogRequest\x1a\".auth.v1.DeleteTimeCardLogResponseB Z\x1emenkyo_go/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_auth_v1_auth_proto_goTypes = []any{
	(UserRole)(0),                           // 0: auth.v1.UserRole
	(DBEnvironment)(0),                      // 1: auth.v1.DBEnvironment
	(*GetAuthorizationURLRequest)(nil),      // 2: auth.v1.GetAuthorizationURLRequest
	(*GetAuthorizationURLResponse)(nil),     // 3: auth.v1.GetAuthorizationURLResponse
	(*ExchangeCodeRequest)(nil),             // 4: auth.v1.ExchangeCodeRequest
	(*ExchangeCodeResponse)(nil),            // 5: auth.v1.ExchangeCodeResponse
	(*GetProfileRequest)(nil),               // 6: auth.v1.GetProfileRequest
	(*GetProfileResponse)(nil),              // 7: auth.v1.GetProfileResponse
	(*RefreshTokenRequest)(nil),             // 8: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),            // 9: auth.v1.RefreshTokenResponse
	(*VerifyTokenRequest)(nil),              // 10: auth.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),             // 11: auth.v1.VerifyTokenResponse
	(*ListUsersRequest)(nil),                // 12: auth.v1.ListUsersRequest
	(*User)(nil),                            // 13: auth.v1.User
	(*ListUsersResponse)(nil),               // 14: auth.v1.ListUsersResponse
	(*UpdateUserRolesRequest)(nil),          // 15: auth.v1.UpdateUserRolesRequest
	(*UpdateUserRolesResponse)(nil),         // 16: auth.v1.UpdateUserRolesResponse
	(*DeleteUserRequest)(nil),               // 17: auth.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),              // 18: auth.v1.DeleteUserResponse
	(*RestoreUserRequest)(nil),              // 19: auth.v1.RestoreUserRequest
	(*RestoreUserResponse)(nil),             // 20: auth.v1.RestoreUserResponse
	(*TimeCard)(nil),                        // 21: auth.v1.TimeCard
	(*GetTimeCardRequest)(nil),              // 22: auth.v1.GetTimeCardRequest
	(*TimeCardResponse)(nil),                // 23: auth.v1.TimeCardResponse
	(*ListTimeCardsRequest)(nil),            // 24: auth.v1.ListTimeCardsRequest
	(*ListTimeCardsResponse)(nil),           // 25: auth.v1.ListTimeCardsResponse
	(*CreateTimeCardRequest)(nil),           // 26: auth.v1.CreateTimeCardRequest
	(*UpdateTimeCardRequest)(nil),           // 27: auth.v1.UpdateTimeCardRequest
	(*DeleteTimeCardRequest)(nil),           // 28: auth.v1.DeleteTimeCardRequest
	(*DeleteTimeCardResponse)(nil),          // 29: auth.v1.DeleteTimeCardResponse
	(*TimeCardLog)(nil),                     // 30: auth.v1.TimeCardLog
	(*GetTimeCardLogRequest)(nil),           // 31: auth.v1.GetTimeCardLogRequest
	(*TimeCardLogResponse)(nil),             // 32: auth.v1.TimeCardLogResponse
	(*ListTimeCardLogsRequest)(nil),         // 33: auth.v1.ListTimeCardLogsRequest
	(*ListTimeCardLogsByCardIDRequest)(nil), // 34: auth.v1.ListTimeCardLogsByCardIDRequest
	(*ListTimeCardLogsResponse)(nil),        // 35: auth.v1.ListTimeCardLogsResponse
	(*CreateTimeCardLogRequest)(nil),        // 36: auth.v1.CreateTimeCardLogRequest
	(*UpdateTimeCardLogRequest)(nil),        // 37: auth.v1.UpdateTimeCardLogRequest
	(*DeleteTimeCardLogRequest)(nil),        // 38: auth.v1.DeleteTimeCardLogRequest
	(*DeleteTimeCardLogResponse)(nil),       // 39: auth.v1.DeleteTimeCardLogResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	13, // 0: auth.v1.ListUsersResponse.users:type_name -> auth.v1.User
	1,  // 1: auth.v1.GetTimeCardRequest.environment:type_name -> auth.v1.DBEnvironment
	21, // 2: auth.v1.TimeCardResponse.timecard:type_name -> auth.v1.TimeCard
	1,  // 3: auth.v1.ListTimeCardsRequest.environment:type_name -> auth.v1.DBEnvironment
	21, // 4: auth.v1.ListTimeCardsResponse.timecards:type_name -> auth.v1.TimeCard
	1,  // 5: auth.v1.GetTimeCardLogRequest.environment:type_name -> auth.v1.DBEnvironment
	30, // 6: auth.v1.TimeCardLogResponse.log:type_name -> auth.v1.TimeCardLog
	1,  // 7: auth.v1.ListTimeCardLogsRequest.environment:type_name -> auth.v1.DBEnvironment
	1,  // 8: auth.v1.ListTimeCardLogsByCardIDRequest.environment:type_name -> auth.v1.DBEnvironment
	30, // 9: auth.v1.ListTimeCardLogsResponse.logs:type_name -> auth.v1.TimeCardLog
	2,  // 10: auth.v1.AuthService.GetAuthorizationURL:input_type -> auth.v1.GetAuthorizationURLRequest
	4,  // 11: auth.v1.AuthService.ExchangeCode:input_type -> auth.v1.ExchangeCodeRequest
	6,  // 12: auth.v1.AuthService.GetProfile:input_type -> auth.v1.GetProfileRequest
	8,  // 13: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	10, // 14: auth.v1.AuthService.VerifyToken:input_type -> auth.v1.VerifyTokenRequest
	12, // 15: auth.v1.AuthService.ListUsers:input_type -> auth.v1.ListUsersRequest
	15, // 16: auth.v1.AuthService.UpdateUserRoles:input_type -> auth.v1.UpdateUserRolesRequest
	17, // 17: auth.v1.AuthService.DeleteUser:input_type -> auth.v1.DeleteUserRequest
	19, // 18: auth.v1.AuthService.RestoreUser:input_type -> auth.v1.RestoreUserRequest
	22, // 19: auth.v1.AuthService.GetTimeCard:input_type -> auth.v1.GetTimeCardRequest
	24, // 20: auth.v1.AuthService.ListTimeCards:input_type -> auth.v1.ListTimeCardsRequest
	26, // 21: auth.v1.AuthService.CreateTimeCard:input_type -> auth.v1.CreateTimeCardRequest
	27, // 22: auth.v1.AuthService.UpdateTimeCard:input_type -> auth.v1.UpdateTimeCardRequest
	28, // 23: auth.v1.AuthService.DeleteTimeCard:input_type -> auth.v1.DeleteTimeCardRequest
	31, // 24: auth.v1.AuthService.GetTimeCardLog:input_type -> auth.v1.GetTimeCardLogRequest
	33, // 25: auth.v1.AuthService.ListTimeCardLogs:input_type -> auth.v1.ListTimeCardLogsRequest
	34, // 26: auth.v1.AuthService.ListTimeCardLogsByCardID:input_type -> auth.v1.ListTimeCardLogsByCardIDRequest
	36, // 27: auth.v1.AuthService.CreateTimeCardLog:input_type -> auth.v1.CreateTimeCardLogRequest
	37, // 28: auth.v1.AuthService.UpdateTimeCardLog:input_type -> auth.v1.UpdateTimeCardLogRequest
	38, // 29: auth.v1.AuthService.DeleteTimeCardLog:input_type -> auth.v1.DeleteTimeCardLogRequest
	3,  // 30: auth.v1.AuthService.GetAuthorizationURL:output_type -> auth.v1.GetAuthorizationURLResponse
	5,  // 31: auth.v1.AuthService.ExchangeCode:output_type -> auth.v1.ExchangeCodeResponse
	7,  // 32: auth.v1.AuthService.GetProfile:output_type -> auth.v1.GetProfileResponse
	9,  // 33: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	11, // 34: auth.v1.AuthService.VerifyToken:output_type -> auth.v1.VerifyTokenResponse
	14, // 35: auth.v1.AuthService.ListUsers:output_type -> auth.v1.ListUsersResponse
	16, // 36: auth.v1.AuthService.UpdateUserRoles:output_type -> auth.v1.UpdateUserRolesResponse
	18, // 37: auth.v1.AuthService.DeleteUser:output_type -> auth.v1.DeleteUserResponse
	20, // 38: auth.v1.AuthService.RestoreUser:output_type -> auth.v1.RestoreUserResponse
	23, // 39: auth.v1.AuthService.GetTimeCard:output_type -> auth.v1.TimeCardResponse
	25, // 40: auth.v1.AuthService.ListTimeCards:output_type -> auth.v1.ListTimeCardsResponse
	23, // 41: auth.v1.AuthService.CreateTimeCard:output_type -> auth.v1.TimeCardResponse
	23, // 42: auth.v1.AuthService.UpdateTimeCard:output_type -> auth.v1.TimeCardResponse
	29, // 43: auth.v1.AuthService.DeleteTimeCard:output_type -> auth.v1.DeleteTimeCardResponse
	32, // 44: auth.v1.AuthService.GetTimeCardLog:output_type -> auth.v1.TimeCardLogResponse
	35, // 45: auth.v1.AuthService.ListTimeCardLogs:output_type -> auth.v1.ListTimeCardLogsResponse
	35, // 46: auth.v1.AuthService.ListTimeCardLogsByCardID:output_type -> auth.v1.ListTimeCardLogsResponse
	32, // 47: auth.v1.AuthService.CreateTimeCardLog:output_type -> auth.v1.TimeCardLogResponse
	32, // 48: auth.v1.AuthService.UpdateTimeCardLog:output_type -> auth.v1.TimeCardLogResponse
	39, // 49: auth.v1.AuthService.DeleteTimeCardLog:output_type -> auth.v1.DeleteTimeCardLogResponse
	30, // [30:50] is the sub-list for method output_type
	10, // [10:30] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
